### ISSUE TITLE
[Diff from Sisal 3.*] Unexpected expression type (which is Conversion node type) 

### ISSUE THREAD

**Issue by datsis** [parsifal-47/sisal-cl#1]
**Steps to reproduce:**
1) Translate following source code to IR:
<pre><code>function Main( M, N, K : integer returns real)
    10
end function</code></pre>

**Expected result:** 
1) successful translation
2) IR contains **Conversion type node** like in Sisal 3.*

**Actual result:**
<pre><code>...\sisal-cl\build\ir1\create.js:24
    throw new Error("Unexpected expression type value " + JSON.stringify(node));
    ^

Error: Unexpected expression type value {"type":"Type","location":{"start":{"offset":41,"line":1,"column":42},"end":{"offset":45,"line":1,"column":46}},"name":"real"}
    at Object.typeFromAST (...\sisal-cl\build\ir1\create.js:24:11)
    at new FunctionValue (...\sisal-cl\build\ir1\nodes\function.js:40:30)
    at new Module (...\sisal-cl\build\module.js:11:21)
    at Object.<anonymous> (...\sisal-cl\build\sisal.js:18:9)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11</code></pre>

**Comment by parsifal-47** [comment]
Implicit casting from any to any primitive type implemented
